import { db } from "./db";
import { products, featuredNumbers, promoCodes } from "../shared/schema";

export async function seedDatabase() {
  const existingProducts = await db.select().from(products);
  if (existingProducts.length > 0) {
    console.log("Database already seeded, skipping...");
    return;
  }

  console.log("Seeding database...");

  await db.insert(products).values([
    {
      id: "honor-magic6-pro",
      name: "Honor Magic6 Pro",
      price: 212900,
      oldPrice: 236900,
      monthlyPrice: 4940,
      brand: "Honor",
      category: "smartphone",
      imageKey: "honor_magic6_pro_green",
      memory: "256GB",
      ram: "12GB",
      color: "Sage Green",
      sim: "Dual",
      rating: 48,
      reviews: 42,
      sku: "225175",
      inStock: true,
      isPreOrder: false,
      badges: [
        { text: "Credit 0%", color: "bg-purple-100 text-purple-700" },
        { text: "Free Gift", color: "bg-orange-100 text-orange-700" },
      ],
      gift: { name: "Wireless Buds Pro", imageKey: "wireless_earbuds", price: 25000 },
      discount: "Save 24,000 ֏",
      colors: [
        { name: "Sage Green", hex: "#8DA399", selected: true },
        { name: "Black", hex: "#1c1e21" },
        { name: "Cyan", hex: "#00bcd4" },
        { name: "Purple", hex: "#9c27b0" },
      ],
      storage: ["256GB", "512GB"],
      specs: {
        Memory: "256 GB",
        Brand: "Honor",
        Storage: "256 GB",
        Model: "Magic6 Pro",
        OS: "Android 14, MagicOS 8",
        Color: "Sage Green",
        "Display Size": '6.8", 1280x2800 pixels',
        "Main Camera": "50 MP + 180 MP + 50 MP",
        Network: "5G / 4G / 3G",
        "Front Camera": "50 MP",
        Battery: "5600 mAh",
        "Card Slots": "2 Nano SIMs",
        "Photo/Video": "4K@60fps, 1080p@240fps",
        Warranty: "24 months",
      },
      description: "Discover the magic of technology with the new Honor Magic6 Pro. Featuring a stunning display, powerful processor, and a revolutionary camera system, it redefines what a smartphone can do.",
    },
    {
      id: "garmin-venu-3s",
      name: "Garmin Venu 3S",
      price: 185000,
      monthlyPrice: 3850,
      brand: "Garmin",
      category: "device",
      imageKey: "garmin_venu_3s_watch",
      badges: [{ text: "Best Seller", color: "bg-blue-100 text-team-blue" }],
      isPreOrder: false,
      colors: [],
      storage: [],
      specs: {},
    },
    {
      id: "wireless-buds",
      name: "Wireless Buds Pro",
      price: 25000,
      oldPrice: 35000,
      monthlyPrice: 1200,
      brand: "Team",
      category: "accessory",
      imageKey: "wireless_earbuds",
      badges: [{ text: "New", color: "bg-blue-100 text-team-blue" }],
      discount: "Save 10,000 ֏",
      isPreOrder: false,
      colors: [],
      storage: [],
      specs: {},
    },
    {
      id: "iphone-15",
      name: "iPhone 15",
      price: 385000,
      monthlyPrice: 8900,
      brand: "Apple",
      category: "smartphone",
      imageKey: "honor_magic6_pro_green",
      memory: "128GB",
      ram: "6GB",
      color: "Black",
      sim: "eSIM",
      badges: [
        { text: "New", color: "bg-blue-100 text-team-blue" },
        { text: "Free Gift", color: "bg-orange-100 text-orange-700" },
      ],
      gift: { name: "Wireless Buds Pro", imageKey: "wireless_earbuds", price: 25000 },
      isPreOrder: true,
      colors: [
        { name: "Black", hex: "#1c1e21", selected: true },
        { name: "Blue", hex: "#4169E1" },
        { name: "Pink", hex: "#FF69B4" },
      ],
      storage: ["128GB", "256GB"],
      specs: {
        Brand: "Apple",
        Model: "iPhone 15",
        OS: "iOS 17",
        "Display Size": '6.1", Super Retina XDR',
        "Main Camera": "48 MP + 12 MP",
        Network: "5G / 4G",
        Battery: "3349 mAh",
      },
    },
    {
      id: "samsung-s24",
      name: "Samsung Galaxy S24",
      price: 320000,
      oldPrice: 350000,
      monthlyPrice: 7400,
      brand: "Samsung",
      category: "smartphone",
      imageKey: "honor_magic6_pro_green",
      memory: "256GB",
      ram: "8GB",
      color: "Gray",
      sim: "Dual",
      badges: [{ text: "Sale", color: "bg-red-100 text-team-red" }],
      discount: "Save 30,000 ֏",
      isPreOrder: false,
      colors: [
        { name: "Gray", hex: "#808080", selected: true },
        { name: "Violet", hex: "#8B5CF6" },
      ],
      storage: ["256GB"],
      specs: {
        Brand: "Samsung",
        Model: "Galaxy S24",
        OS: "Android 14, One UI 6",
        "Display Size": '6.2", Dynamic AMOLED',
        "Main Camera": "50 MP + 12 MP + 10 MP",
        Network: "5G / 4G",
        Battery: "4000 mAh",
      },
    },
    {
      id: "pixel-8",
      name: "Google Pixel 8",
      price: 290000,
      monthlyPrice: 6700,
      brand: "Google",
      category: "smartphone",
      imageKey: "honor_magic6_pro_green",
      memory: "128GB",
      ram: "8GB",
      color: "Obsidian",
      sim: "eSIM",
      badges: [{ text: "Exclusive", color: "bg-yellow-100 text-yellow-700" }],
      isPreOrder: false,
      colors: [
        { name: "Obsidian", hex: "#333333", selected: true },
        { name: "Hazel", hex: "#8B7355" },
      ],
      storage: ["128GB", "256GB"],
      specs: {
        Brand: "Google",
        Model: "Pixel 8",
        OS: "Android 14",
        "Display Size": '6.2", OLED',
        "Main Camera": "50 MP + 12 MP",
        Network: "5G / 4G",
        Battery: "4575 mAh",
      },
    },
    {
      id: "xiaomi-14",
      name: "Xiaomi 14",
      price: 250000,
      monthlyPrice: 5800,
      brand: "Xiaomi",
      category: "smartphone",
      imageKey: "honor_magic6_pro_green",
      memory: "512GB",
      ram: "12GB",
      color: "White",
      sim: "SIM",
      badges: [],
      isPreOrder: false,
      colors: [
        { name: "White", hex: "#FFFFFF", selected: true },
        { name: "Black", hex: "#1c1e21" },
      ],
      storage: ["256GB", "512GB"],
      specs: {
        Brand: "Xiaomi",
        Model: "Xiaomi 14",
        OS: "Android 14, MIUI 15",
        "Display Size": '6.36", AMOLED',
        "Main Camera": "50 MP + 50 MP + 50 MP",
        Network: "5G / 4G",
        Battery: "4610 mAh",
      },
    },
    {
      id: "iphone-15-pro",
      name: "iPhone 15 Pro",
      price: 540000,
      monthlyPrice: 12500,
      brand: "Apple",
      category: "smartphone",
      imageKey: "honor_magic6_pro_green",
      memory: "256GB",
      ram: "8GB",
      color: "Titanium",
      sim: "eSIM",
      badges: [{ text: "Best Seller", color: "bg-blue-100 text-team-blue" }],
      isPreOrder: false,
      colors: [
        { name: "Natural Titanium", hex: "#C4B5A0", selected: true },
        { name: "Blue Titanium", hex: "#394E6A" },
        { name: "Black Titanium", hex: "#3A3A3C" },
      ],
      storage: ["256GB", "512GB", "1TB"],
      specs: {
        Brand: "Apple",
        Model: "iPhone 15 Pro",
        OS: "iOS 17",
        "Display Size": '6.1", Super Retina XDR ProMotion',
        "Main Camera": "48 MP + 12 MP + 12 MP",
        Network: "5G / 4G",
        Battery: "3274 mAh",
      },
    },
    {
      id: "samsung-a55",
      name: "Samsung Galaxy A55",
      price: 160000,
      monthlyPrice: 3700,
      brand: "Samsung",
      category: "smartphone",
      imageKey: "honor_magic6_pro_green",
      memory: "128GB",
      ram: "8GB",
      color: "Blue",
      sim: "Dual",
      badges: [{ text: "Credit 0%", color: "bg-purple-100 text-purple-700" }],
      isPreOrder: false,
      colors: [
        { name: "Blue", hex: "#4169E1", selected: true },
        { name: "Lilac", hex: "#C8A2C8" },
      ],
      storage: ["128GB", "256GB"],
      specs: {
        Brand: "Samsung",
        Model: "Galaxy A55",
        OS: "Android 14, One UI 6",
        "Display Size": '6.6", Super AMOLED',
        "Main Camera": "50 MP + 12 MP + 5 MP",
        Network: "5G / 4G",
        Battery: "5000 mAh",
      },
    },
    {
      id: "ipad-air",
      name: "iPad Air 5",
      price: 280000,
      monthlyPrice: 6500,
      brand: "Apple",
      category: "device",
      imageKey: "honor_magic6_pro_green",
      badges: [{ text: "Combo Offer", color: "bg-indigo-100 text-indigo-700" }],
      isPreOrder: false,
      colors: [],
      storage: [],
      specs: {},
    },
    {
      id: "sony-xm5",
      name: "Sony WH-1000XM5",
      price: 145000,
      monthlyPrice: 3300,
      brand: "Sony",
      category: "accessory",
      imageKey: "wireless_earbuds",
      badges: [{ text: "Credit 0%", color: "bg-purple-100 text-purple-700" }],
      isPreOrder: false,
      colors: [],
      storage: [],
      specs: {},
    },
  ]);

  await db.insert(featuredNumbers).values([
    { type: "Platinum", number: "099 68 33 33", price: 112000, oldPrice: 140000, discount: 20 },
    { type: "Gold", number: "091 11 22 33", price: 80000, oldPrice: 100000, discount: 20 },
    { type: "Silver", number: "096 55 44 55", price: 40000, oldPrice: 50000, discount: 20 },
    { type: "Bronze", number: "033 99 88 77", price: 15000, oldPrice: 20000, discount: 25 },
    { type: "Platinum", number: "099 77 00 77", price: 112000, oldPrice: 140000, discount: 20 },
    { type: "Gold", number: "091 55 55 55", price: 85000, oldPrice: 105000, discount: 19 },
    { type: "Silver", number: "096 11 11 11", price: 45000, oldPrice: 55000, discount: 18 },
    { type: "Bronze", number: "033 22 22 22", price: 18000, oldPrice: 22000, discount: 18 },
  ]);

  await db.insert(promoCodes).values([
    { code: "XXXYYY", discountPercent: 5, fullPaymentOnly: true, active: true },
    { code: "WELCOME10", discountPercent: 10, fullPaymentOnly: false, active: true },
  ]);

  console.log("Database seeded successfully!");
}
